{
  "cells": [
   {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
     "#  逻辑回归与数据可视化"
    ]
   },
   {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
     "## Titanic 逻辑回归分析"
    ]
   },
   {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
     "### 导入Titanic数据"
    ]
   },
   {
    "cell_type": "code",
    "execution_count": 1,
    "metadata": {},
    "outputs": [],
    "source": [
     "import seaborn as sns"
    ]
   },
   {
    "cell_type": "code",
    "execution_count": 2,
    "metadata": {},
    "outputs": [
     {
      "data": {
       "text/html": [
        "<div>\n",
        "<style scoped>\n",
        "    .dataframe tbody tr th:only-of-type {\n",
        "        vertical-align: middle;\n",
        "    }\n",
        "\n",
        "    .dataframe tbody tr th {\n",
        "        vertical-align: top;\n",
        "    }\n",
        "\n",
        "    .dataframe thead th {\n",
        "        text-align: right;\n",
        "    }\n",
        "</style>\n",
        "<table border=\"1\" class=\"dataframe\">\n",
        "  <thead>\n",
        "    <tr style=\"text-align: right;\">\n",
        "      <th></th>\n",
        "      <th>survived</th>\n",
        "      <th>pclass</th>\n",
        "      <th>sex</th>\n",
        "      <th>age</th>\n",
        "      <th>sibsp</th>\n",
        "      <th>parch</th>\n",
        "      <th>fare</th>\n",
        "      <th>embarked</th>\n",
        "      <th>class</th>\n",
        "      <th>who</th>\n",
        "      <th>adult_male</th>\n",
        "      <th>deck</th>\n",
        "      <th>embark_town</th>\n",
        "      <th>alive</th>\n",
        "      <th>alone</th>\n",
        "    </tr>\n",
        "  </thead>\n",
        "  <tbody>\n",
        "    <tr>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>3</td>\n",
        "      <td>male</td>\n",
        "      <td>22.0</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>7.2500</td>\n",
        "      <td>S</td>\n",
        "      <td>Third</td>\n",
        "      <td>man</td>\n",
        "      <td>True</td>\n",
        "      <td>NaN</td>\n",
        "      <td>Southampton</td>\n",
        "      <td>no</td>\n",
        "      <td>False</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>1</td>\n",
        "      <td>1</td>\n",
        "      <td>1</td>\n",
        "      <td>female</td>\n",
        "      <td>38.0</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>71.2833</td>\n",
        "      <td>C</td>\n",
        "      <td>First</td>\n",
        "      <td>woman</td>\n",
        "      <td>False</td>\n",
        "      <td>C</td>\n",
        "      <td>Cherbourg</td>\n",
        "      <td>yes</td>\n",
        "      <td>False</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>2</td>\n",
        "      <td>1</td>\n",
        "      <td>3</td>\n",
        "      <td>female</td>\n",
        "      <td>26.0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>7.9250</td>\n",
        "      <td>S</td>\n",
        "      <td>Third</td>\n",
        "      <td>woman</td>\n",
        "      <td>False</td>\n",
        "      <td>NaN</td>\n",
        "      <td>Southampton</td>\n",
        "      <td>yes</td>\n",
        "      <td>True</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>3</td>\n",
        "      <td>1</td>\n",
        "      <td>1</td>\n",
        "      <td>female</td>\n",
        "      <td>35.0</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>53.1000</td>\n",
        "      <td>S</td>\n",
        "      <td>First</td>\n",
        "      <td>woman</td>\n",
        "      <td>False</td>\n",
        "      <td>C</td>\n",
        "      <td>Southampton</td>\n",
        "      <td>yes</td>\n",
        "      <td>False</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>4</td>\n",
        "      <td>0</td>\n",
        "      <td>3</td>\n",
        "      <td>male</td>\n",
        "      <td>35.0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>8.0500</td>\n",
        "      <td>S</td>\n",
        "      <td>Third</td>\n",
        "      <td>man</td>\n",
        "      <td>True</td>\n",
        "      <td>NaN</td>\n",
        "      <td>Southampton</td>\n",
        "      <td>no</td>\n",
        "      <td>True</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>886</td>\n",
        "      <td>0</td>\n",
        "      <td>2</td>\n",
        "      <td>male</td>\n",
        "      <td>27.0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>13.0000</td>\n",
        "      <td>S</td>\n",
        "      <td>Second</td>\n",
        "      <td>man</td>\n",
        "      <td>True</td>\n",
        "      <td>NaN</td>\n",
        "      <td>Southampton</td>\n",
        "      <td>no</td>\n",
        "      <td>True</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>887</td>\n",
        "      <td>1</td>\n",
        "      <td>1</td>\n",
        "      <td>female</td>\n",
        "      <td>19.0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>30.0000</td>\n",
        "      <td>S</td>\n",
        "      <td>First</td>\n",
        "      <td>woman</td>\n",
        "      <td>False</td>\n",
        "      <td>B</td>\n",
        "      <td>Southampton</td>\n",
        "      <td>yes</td>\n",
        "      <td>True</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>888</td>\n",
        "      <td>0</td>\n",
        "      <td>3</td>\n",
        "      <td>female</td>\n",
        "      <td>NaN</td>\n",
        "      <td>1</td>\n",
        "      <td>2</td>\n",
        "      <td>23.4500</td>\n",
        "      <td>S</td>\n",
        "      <td>Third</td>\n",
        "      <td>woman</td>\n",
        "      <td>False</td>\n",
        "      <td>NaN</td>\n",
        "      <td>Southampton</td>\n",
        "      <td>no</td>\n",
        "      <td>False</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>889</td>\n",
        "      <td>1</td>\n",
        "      <td>1</td>\n",
        "      <td>male</td>\n",
        "      <td>26.0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>30.0000</td>\n",
        "      <td>C</td>\n",
        "      <td>First</td>\n",
        "      <td>man</td>\n",
        "      <td>True</td>\n",
        "      <td>C</td>\n",
        "      <td>Cherbourg</td>\n",
        "      <td>yes</td>\n",
        "      <td>True</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>890</td>\n",
        "      <td>0</td>\n",
        "      <td>3</td>\n",
        "      <td>male</td>\n",
        "      <td>32.0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>7.7500</td>\n",
        "      <td>Q</td>\n",
        "      <td>Third</td>\n",
        "      <td>man</td>\n",
        "      <td>True</td>\n",
        "      <td>NaN</td>\n",
        "      <td>Queenstown</td>\n",
        "      <td>no</td>\n",
        "      <td>True</td>\n",
        "    </tr>\n",
        "  </tbody>\n",
        "</table>\n",
        "<p>891 rows × 15 columns</p>\n",
        "</div>"
       ],
       "text/plain": [
        "     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \\\n",
        "0           0       3    male  22.0      1      0   7.2500        S   Third   \n",
        "1           1       1  female  38.0      1      0  71.2833        C   First   \n",
        "2           1       3  female  26.0      0      0   7.9250        S   Third   \n",
        "3           1       1  female  35.0      1      0  53.1000        S   First   \n",
        "4           0       3    male  35.0      0      0   8.0500        S   Third   \n",
        "..        ...     ...     ...   ...    ...    ...      ...      ...     ...   \n",
        "886         0       2    male  27.0      0      0  13.0000        S  Second   \n",
        "887         1       1  female  19.0      0      0  30.0000        S   First   \n",
        "888         0       3  female   NaN      1      2  23.4500        S   Third   \n",
        "889         1       1    male  26.0      0      0  30.0000        C   First   \n",
        "890         0       3    male  32.0      0      0   7.7500        Q   Third   \n",
        "\n",
        "       who  adult_male deck  embark_town alive  alone  \n",
        "0      man        True  NaN  Southampton    no  False  \n",
        "1    woman       False    C    Cherbourg   yes  False  \n",
        "2    woman       False  NaN  Southampton   yes   True  \n",
        "3    woman       False    C  Southampton   yes  False  \n",
        "4      man        True  NaN  Southampton    no   True  \n",
        "..     ...         ...  ...          ...   ...    ...  \n",
        "886    man        True  NaN  Southampton    no   True  \n",
        "887  woman       False    B  Southampton   yes   True  \n",
        "888  woman       False  NaN  Southampton    no  False  \n",
        "889    man        True    C    Cherbourg   yes   True  \n",
        "890    man        True  NaN   Queenstown    no   True  \n",
        "\n",
        "[891 rows x 15 columns]"
       ]
      },
      "execution_count": 2,
      "metadata": {},
      "output_type": "execute_result"
     }
    ],
    "source": [
     "sns.load_dataset(\"titanic\")"
    ]
   },
   {
    "cell_type": "code",
    "execution_count": 3,
    "metadata": {},
    "outputs": [],
    "source": [
     "titanic = sns.load_dataset(\"titanic\")"
    ]
   },
   {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
     "## 变量初步可视化及筛选"
    ]
   },
   {
    "cell_type": "code",
    "execution_count": 4,
    "metadata": {},
    "outputs": [
     {
      "data": {
       "image/png": "iVBORw0KGgoAAAANSUhEUgAAAYIAAAEGCAYAAABo25JHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjEsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy8QZhcZAAAW5ElEQVR4nO3deZgddZ3v8feXhFUgLGmWkKUzGtSwY5uAoCIgEBgBHVmCjANXzCyijgtccGFY9I6oV8UBL/IwXNBBHQEHM+xzESRAGOmwJCQIZFikCRfCIip7ku/8cSpweu+T9OlO5/d+Pc95UvWrX/3Ot7s653Oq6lSdyEwkSeVaZ7gLkCQNL4NAkgpnEEhS4QwCSSqcQSBJhRs93AWsirFjx2Zra+twlyFJI8q8efOeycyWru0jMghaW1tpb28f7jIkaUSJiMd6avfQkCQVziCQpMIZBJJUOINAkgpnEEhS4QwCSSqcQSBJhWtqEETERRHxdETc18vyiIjvR8TiiJgfEbsP5vO3nnI1radcDcCy5Su6LV+xIlm+ovttuHvq+3oPbY5Zs/J3LGlkavYFZRcD5wI/6mX5DGBK9ZgO/J/q39VW/+K0cnrrTdfntD/fgUN23pbzblrM+Tf/F8szOX6vVk468B3c9Nun+cqV9/HkCy/zwalb8+0jduG5F1/j7//1Hu7+3e/ZYdymfOfIXZm05Ub8zyvmc/X8J9ly4/WKHXNZXZCs/B0/+o1DBmPzSRpC0ewvpomIVuCqzNyxh2U/BG7OzJ9W8w8A+2Tmk32N2dbWln1dWdzXO9T1Rq/DD47ZnRN+1Hn9c4/ZjVOvWMAfX132RtsJe09m0ZN/4Pb/evaNth2325QDpm7Dd/7jwSEYczdO+NG8zmPO3I1Tf7HmjNmVQSCtuSJiXma2dW0f7ltMbAc8XjffUbV1C4KImAXMApg4ceIqP+Fry1bwq98+3a19zoPPdHohBLi34/csWvKHTm33PfEHttp4/SEac2n3MR9aOvAxN9mg6WNKGvmG+2Rx9NDW4y5KZl6QmW2Z2dbS0u2eSQO20XqjOGTnbbu1H7jj1my+0bqd2qZP3pJpk7fo1NY2aXOm/9mWwzfmDtsOfMwubc0YU9LIN9xB0AFMqJsfDyxZ3UF7Ozzxjm024fxj38VebxvL//rwTozffEO22XQDvnLIO9n3HVtzwcfb2HG7TRmz4brMnDaBE/d9G9/4i53Z7x1bscn6o3nvlLF896hd+R97T+a497Sy+UbrDv2Y79xqjRlT0tphuM8RHAKcCBxM7STx9zNzWn9j9neOQJLU3bCcI4iInwL7AGMjogP4B2BdgMw8H7iGWggsBl4Cjm9mPZKk7poaBJk5s5/lCXyqmTVIkvo23OcIJEnDzCCQpMIZBJJUOINAkgpnEEhS4QwCSSqcQSBJhTMIJKlwBoEkFc4gkKTCGQSSVDiDQJIKZxBIUuEMAkkqnEEgSYUzCCSpcAaBJBXOIJCkwhkEklQ4g0CSCmcQSFLhDAJJKpxBIEmFMwgkqXAGgSQVziCQpMIZBJJUOINAkgpnEEhS4QwCSSpc04MgIg6KiAciYnFEnNLD8okRcVNE3B0R8yPi4GbXJEl6U1ODICJGAecBM4CpwMyImNql21eAn2fmbsDRwA+aWZMkqbNm7xFMAxZn5sOZ+RrwM+CwLn0S2LSaHgMsaXJNkqQ6zQ6C7YDH6+Y7qrZ6pwPHRkQHcA3w6Z4GiohZEdEeEe1Lly5tRq2SVKRmB0H00JZd5mcCF2fmeOBg4McR0a2uzLwgM9sys62lpaUJpUpSmZodBB3AhLr58XQ/9PMJ4OcAmTkX2AAY2+S6JEmVZgfBncCUiJgcEetROxk8u0uf3wH7AUTEO6kFgcd+JGmINDUIMnMZcCJwPXA/tU8HLYyIMyPi0KrbF4BPRsS9wE+B4zKz6+EjSVKTjG72E2TmNdROAte3nVY3vQjYq9l1SJJ65pXFklQ4g0CSCmcQSFLhDAJJKpxBIEmFMwgkqXAGgSQVziCQpMIZBJJUOINAkgpnEEhS4QwCSSqcQSBJhTMIJKlwBoEkFc4gkKTCGQSSVDiDQJIKZxBIUuEMAkkqnEEgSYUzCCSpcAaBJBXOIJCkwhkEklQ4g0CSCmcQSFLhDAJJKtyAgyAito6If46Ia6v5qRHxieaVJkkaCo3sEVwMXA+Mq+YfBP6+v5Ui4qCIeCAiFkfEKb30OTIiFkXEwoj4SQM1SZJWUyNBMDYzfw6sAMjMZcDyvlaIiFHAecAMYCowMyKmdukzBTgV2Cszd2AA4SJJGjyNBMGLEbElkAARsQfwQj/rTAMWZ+bDmfka8DPgsC59Pgmcl5nPA2Tm0w3UJElaTaMb6Pt5YDbw1oi4DWgBPtrPOtsBj9fNdwDTu/TZHqAacxRwemZe10BdkqTVMOAgyMy7IuL9wNuBAB7IzNf7WS16GqqHGqYA+wDjgTkRsWNm/r7TQBGzgFkAEydOHGjZkqR+9BsEEfGRXhZtHxFk5i/6WL0DmFA3Px5Y0kOfO6pQeSQiHqAWDHfWd8rMC4ALANra2rqGiSRpFQ1kj+BDfSxLoK8guBOYEhGTgSeAo4FjuvS5EpgJXBwRY6kdKnp4AHVJkgZBv0GQmcev6uCZuSwiTqT2sdNRwEWZuTAizgTaM3N2teyAiFhE7VNIJ2Xms6v6nJKkxkTmwI+yRMQhwA7ABivbMvPMJtTVp7a2tmxvbx/qp5WkES0i5mVmW9f2Rq4sPh84Cvg0tZPARwCTBq1CSdKwaOQ6gvdk5seB5zPzDGBPOp8IliSNQI0EwcvVvy9FxDjgdWDy4JckSRpKjVxQdlVEbAZ8C7iL2ieGLmxKVZKkIdPIBWVnVZNXRMRVwAaZ2d8tJiRJa7gBB0F1A7lDgNaV61UXlH2nOaVJkoZCI4eG/h14BVhAdQdSSdLI10gQjM/MnZtWiSRpWDTyqaFrI+KAplUiSRoWjewR3AH8W0SsQ+2jowFkZm7alMokSUOikSD439QuIluQjdyXQpK0Rmvk0NBDwH2GgCStXRrZI3gSuDkirgVeXdnox0claWRrJAgeqR7rVQ9J0lqgkSuLz+hreUT8U2Z+evVLkiQNpUbOEfRnr0EcS5I0RAYzCCRJI5BBIEmFG8wgiEEcS5I0RBr5qsoj+mk7Z1AqkiQNqUb2CE7tqy0zL17taiRJQ67fj49GxAzgYGC7iPh+3aJNgWXNKkySNDQGch3BEmAecGj170p/BD7XjKIkSUOn3yDIzHuBeyPiXzLTPQBJWssM5NDQAmpfVE9E9w8G+WU1kjSyDeTQ0J83vQpJ0rAZyKGhx4aiEEnS8BjwTeci4o9Uh4io3X10XeBFv6FMkka2Ru4+ukn9fEQcDkwb9IokSUNqlW8xkZlXAvsOYi2SpGHQyKGhj9TNrgO08eahor7WO4ja7SdGARdm5jd66fdR4DLg3ZnZPtC6JEmrp5FvKPtQ3fQy4FHgsL5WiIhRwHnAB4EO4M6ImJ2Zi7r02wT4DPCfDdQjSRoEjZwjOH4Vxp8GLM7MhwEi4mfUwmNRl35nAd8EvrgKzyFJWg0DuaDsn+jjEFBmfqaP1bcDHq+b7wCmdxl/N2BCZl4VEb0GQUTMAmYBTJw4sb+yJUkDNJCTxe3U7jG0AbA78FD12BVY3s+6PX1HwRuhEhHrAN8FvtBfEZl5QWa2ZWZbS0vLAMqWJA3EQC4ouwQgIo4DPpCZr1fz5wM39LN6BzChbn48tZvYrbQJsCNwc3X7im2A2RFxqCeMJWloNPLx0XHUXrhX2rhq68udwJSImBwR6wFHA7NXLszMFzJzbGa2ZmYrcAdgCEjSEGrkU0PfAO6OiJuq+fcDp/e1QmYui4gTgeupfXz0osxcGBFnAu2ZObuv9SVJzReZ/V4K8GbniHHAXwL3AxsBSzLzlibV1qu2trZsb3enQZIaERHzMrOta3sjF5SdAHyW2nH+e4A9gLl4dbEkjWiNnCP4LPBu4LHM/ACwG7C0KVVJkoZMI0HwSma+AhAR62fmb4G3N6csSdJQaeRkcUdEbAZcCfxHRDxP54+CSpJGoEZuMfHhavL06pNDY4DrmlKVJGnINLJH8IbM/PVgFyJJGh6r/H0EkqS1g0EgSYUzCCSpcAaBJBXOIJCkwhkEklQ4g0CSCmcQSFLhDAJJKpxBIEmFMwgkqXAGgSQVziCQpMIZBJJUOINAkgpnEEhS4QwCSSqcQSBJhTMIJKlwBoEkFc4gkKTCGQSSVDiDQJIKZxBIUuGaHgQRcVBEPBARiyPilB6Wfz4iFkXE/Ii4MSImNbsmSdKbmhoEETEKOA+YAUwFZkbE1C7d7gbaMnNn4HLgm82sSZLUWbP3CKYBizPz4cx8DfgZcFh9h8y8KTNfqmbvAMY3uSZJUp1mB8F2wON18x1VW28+AVzb04KImBUR7RHRvnTp0kEsUZLK1uwgiB7asseOEccCbcC3elqemRdkZltmtrW0tAxiiZJUttFNHr8DmFA3Px5Y0rVTROwPfBl4f2a+2uSaJEl1mr1HcCcwJSImR8R6wNHA7PoOEbEb8EPg0Mx8usn1SJK6aGoQZOYy4ETgeuB+4OeZuTAizoyIQ6tu3wI2Bi6LiHsiYnYvw0mSmqDZh4bIzGuAa7q0nVY3vX+za5Ak9c4riyWpcAaBJBXOIJCkwhkEklQ4g0CSCmcQSFLhDAJJKpxBIEmFMwgkqXAGgSQVziCQpMIZBJJUOINAkgpnEEhS4QwCSSqcQSBJhTMIJKlwBoEkFc4gkKTCGQSSVDiDQJIKZxBIUuEMAkkqnEEgSYUzCCSpcAaBJBXOIJCkwhkEklQ4g0CSCtf0IIiIgyLigYhYHBGn9LB8/Yj412r5f0ZEa7Nr0ghx+hg444za9Osvd1/++ivd25a9BiuWd25bsbzW3m19x+T0zWq/50H2yCOP8KnrP1V7qhWvs2zFss5l5QpeW969rleWdf+5Xl3+KpnZqc0xa2Ou/B2vruj6JIMpIkYBDwIfBDqAO4GZmbmors/fATtn5t9ExNHAhzPzqL7GbWtry/b29qbVrWHW2wvTpL3hLy6EWAeu+AQ8Oge2+DM49FyYMB2u+QLcfSms9xbY9ysw7ZNw54Vw41nw2ouw60w45LvQcSf88u/guYfLHrPb7/2FQdl8O12yU7e2DUdvyPE7HM/f7vq3XPfodZz9m7N57pXn2G/ifnxtr6/xxJ+e4JQ5p/Dg8w8ydcupnP3esxm74Vi+dOuXuPnxm2nZqIUvT/8y+07cl3PuOodL778UoNgxX17W/c3Bgr9a0O+2iYh5mdnWrb3JQbAncHpmHljNnwqQmf9Y1+f6qs/ciBgN/H+gJfsozCBYy/X1DnWHD8M6o2HBZW+2bTIO3vdFuPrznfseczn85Aig7k/p4G/Drd+DP3QM05gnwdWf6zzmxy6DS4/sMua34NZzmj9mV6sZBmfccgaXP3J5r8u/t8/3OPmWk3ltxZvviP96579mzhNzWPTsG+8P2X2r3dlp7E5csuiSN9o2Gr0RZ7znDE665STH7MFZe57F4dsf3uty6D0IRve51urbDni8br4DmN5bn8xcFhEvAFsCz9R3iohZwCyAiRMnNqteremW3F17Maz3xyXwu7nd+z54LZ1eCKHWr+sL4ZCOeXv3MR+4bvjGHGR9hQDAbUtu6/RCCLDw2YXc/+z9ndoWPbuIdaLzkeuXlr3E3Ce7b5NmjHnrklu7jXnfM/cNfMwlQzNmvdPmntZvEPSm2ecIooe2ru/0B9KHzLwgM9sys62lpWVQitMI1PpeaN27c9sWb4UpB3Zui1Gw05HdXzinHABbTlnzx3zbgUMz5iA7a8+z+lx+UOtBbLzuxp3apm0zjbZtOr9Jffc272baNtM6tW22/mYcMOmAIRlzRuuMbmNO33b6wMdsHZox6/3yfb/sc3lfmr1H0AFMqJsfDyzppU9HdWhoDPBck+vSSLPhFvC2/eHArwNRO1n60A2w1Ttrh2a2ngrPPwLt/xfW3wT2/TJM2gOOuBh+9TV45QV413Gw81Gw7S5wzUnw1MI1d8xdjoJxTR7z5S7/zQbhHMHh2x/OV+d+tVv7+I3Hc8JOJzBt22mc84Fz+Hb7t3nqpac4ePLBHDv1WGZMnsGZc89k/jPz2X2r3fnqHl9lzPpjeO6V57jhsRsY95ZxnDztZHbbaje+NP1LXLLwEoIodswn/vREt9/x5MmTV3m7NfscwWhqJ4v3A56gdrL4mMxcWNfnU8BOdSeLP5KZR/Y1rucIJKlxw3KOoDrmfyJwPTAKuCgzF0bEmUB7Zs4G/hn4cUQsprYncHQza5IkddbsQ0Nk5jXANV3aTqubfgU4otl1SJJ65pXFklQ4g0CSCmcQSFLhDAJJKpxBIEmFMwgkqXAGgSQVrqlXFjdLRCwFHhvuOppoLF1uuqcRw203sq3t229SZna7WduIDIK1XUS093QZuNZ8bruRrdTt56EhSSqcQSBJhTMI1kwXDHcBWmVuu5GtyO3nOQJJKpx7BJJUOINAkgpnEEgqSkRcHBEf7aF9XERcXk3vExFX9bL+oxExttl1DqWmfzGNJI0EmbkE6BYQJXCPYAhFRGtE/DYiLoyI+yLi0ojYPyJui4iHImJa9bg9Iu6u/n17te5xEfGLiLiu6vvN4f551jYRcXJEfKaa/m5E/Kqa3i8i/iUiZkbEgmrbnV233p8i4uyImBcR/6/ahjdHxMMRcWjVpzUi5kTEXdXjPVX7PlXfy6u/jUsjIobj519bRcTHI2J+RNwbET+umt9X/f96eOXeQbWN7uth/S0j4obq/+QPgbVv+2SmjyF6AK3AMmAnaiE8D7iI2h/WYcCVwKbA6Kr//sAV1fRxwMPAGGADarfYmDDcP9Pa9AD2AC6rpucAvwHWBf6hevwOaKG2J/0r4PCqbwIzqul/A26o1tsFuKdq3wjYoJqeQu07uwH2AV4Axld/E3OBvYf7d7G2PIAdgAeAsdX8FsDFwGXV73sqsLha1grcV7ddrqqmvw+cVk0fUm3vscP9sw3mw0NDQ++RzFwAEBELgRszMyNiAbU/xDHAJRExhdof3Lp1696YmS9U6y4CJgGPD2Xxa7l5wLsiYhPgVeAuoA14L/DvwM2ZuRQgIi4F3kctvF8DrqvGWAC8mpmv121TqG3HcyNiV2A5sH3d8/4mMzuqce+p1rm1ST9jafYFLs/MZwAy87lqh+vKzFwBLIqIrfsZ433AR6r1r46I55tZ8HDw0NDQe7VuekXd/Apq7zTPAm7KzB2BD1F799/TusvxHM+gyszXgUeB44Hbqe0VfAB4K7W9gd68ntXbReq2afVCs3IbfQ54itpeQhuwXt36btfmCWpvqLp6tUuf/qzVF1wZBGueMcAT1fRxw1hHqW4Bvlj9Owf4G+Ae4A7g/RExNiJGATOBXzcw7hjgySoc/hIYNahVqzc3AkdGxJYAEbHFKoxxC/Cxav0ZwOaDV96awSBY83wT+MeIuA1fLIbDHGBbYG5mPgW8AszJzCeBU4GbgHuBuzLzlw2M+wPgryLiDmqHhV4c3LLVk8xcCHwd+HVE3At8ZxWGOYPayeW7gAPoe+9wRPIWE5JUOPcIJKlwBoEkFc4gkKTCGQSSVDiDQJIKZxBIgyQi/jTcNUirwiCQpMIZBNIA9Xd30mr669VdLu9YeQ+biJgUETdWd8C8MSImDt9PIXVnEEgDdwu1G9BB7X5BG0fEusDe1K5IfgtwR2buUvX9ZNX3XOBHmbkzcCm1u1lKawyDQBq4rncnncubdyedQ+0upFfV9W2tpvcEflJN/5hacEhrDO9yKA1QdWvpR3nz7qTzefPupPfT+S6kfd1F1Pu6aI3iHoHUmB7vTpp937TrduDoavpj+F0DWsMYBFJjerw7aT/rfAY4PiLmU7sF9WebW6LUGO8+KkmFc49AkgpnEEhS4QwCSSqcQSBJhTMIJKlwBoEkFc4gkKTC/Tc8HTD+8edSKwAAAABJRU5ErkJggg==\n",
       "text/plain": [
        "<Figure size 432x288 with 1 Axes>"
       ]
      },
      "metadata": {
       "needs_background": "light"
      },
      "output_type": "display_data"
     }
    ],
    "source": [
     "sns.swarmplot(x=\"who\", y=\"adult_male\", data=titanic);"
    ]
   },
   {
    "cell_type": "code",
    "execution_count": 5,
    "metadata": {},
    "outputs": [],
    "source": [
     "x=[2,8,10,11,12,13]\n",
     "titanic.drop(titanic.columns[x], axis=1, inplace=True)"
    ]
   },
   {
    "cell_type": "code",
    "execution_count": 6,
    "metadata": {},
    "outputs": [],
    "source": [
     "titanic = titanic.dropna()#删除缺失值"
    ]
   },
   {
    "cell_type": "code",
    "execution_count": 7,
    "metadata": {},
    "outputs": [
     {
      "data": {
       "text/html": [
        "<div>\n",
        "<style scoped>\n",
        "    .dataframe tbody tr th:only-of-type {\n",
        "        vertical-align: middle;\n",
        "    }\n",
        "\n",
        "    .dataframe tbody tr th {\n",
        "        vertical-align: top;\n",
        "    }\n",
        "\n",
        "    .dataframe thead th {\n",
        "        text-align: right;\n",
        "    }\n",
        "</style>\n",
        "<table border=\"1\" class=\"dataframe\">\n",
        "  <thead>\n",
        "    <tr style=\"text-align: right;\">\n",
        "      <th></th>\n",
        "      <th>survived</th>\n",
        "      <th>pclass</th>\n",
        "      <th>age</th>\n",
        "      <th>sibsp</th>\n",
        "      <th>parch</th>\n",
        "      <th>fare</th>\n",
        "      <th>embarked</th>\n",
        "      <th>who</th>\n",
        "      <th>alone</th>\n",
        "    </tr>\n",
        "  </thead>\n",
        "  <tbody>\n",
        "    <tr>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>3</td>\n",
        "      <td>22.0</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>7.2500</td>\n",
        "      <td>S</td>\n",
        "      <td>man</td>\n",
        "      <td>False</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>1</td>\n",
        "      <td>1</td>\n",
        "      <td>1</td>\n",
        "      <td>38.0</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>71.2833</td>\n",
        "      <td>C</td>\n",
        "      <td>woman</td>\n",
        "      <td>False</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>2</td>\n",
        "      <td>1</td>\n",
        "      <td>3</td>\n",
        "      <td>26.0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>7.9250</td>\n",
        "      <td>S</td>\n",
        "      <td>woman</td>\n",
        "      <td>True</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>3</td>\n",
        "      <td>1</td>\n",
        "      <td>1</td>\n",
        "      <td>35.0</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>53.1000</td>\n",
        "      <td>S</td>\n",
        "      <td>woman</td>\n",
        "      <td>False</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>4</td>\n",
        "      <td>0</td>\n",
        "      <td>3</td>\n",
        "      <td>35.0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>8.0500</td>\n",
        "      <td>S</td>\n",
        "      <td>man</td>\n",
        "      <td>True</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>885</td>\n",
        "      <td>0</td>\n",
        "      <td>3</td>\n",
        "      <td>39.0</td>\n",
        "      <td>0</td>\n",
        "      <td>5</td>\n",
        "      <td>29.1250</td>\n",
        "      <td>Q</td>\n",
        "      <td>woman</td>\n",
        "      <td>False</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>886</td>\n",
        "      <td>0</td>\n",
        "      <td>2</td>\n",
        "      <td>27.0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>13.0000</td>\n",
        "      <td>S</td>\n",
        "      <td>man</td>\n",
        "      <td>True</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>887</td>\n",
        "      <td>1</td>\n",
        "      <td>1</td>\n",
        "      <td>19.0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>30.0000</td>\n",
        "      <td>S</td>\n",
        "      <td>woman</td>\n",
        "      <td>True</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>889</td>\n",
        "      <td>1</td>\n",
        "      <td>1</td>\n",
        "      <td>26.0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>30.0000</td>\n",
        "      <td>C</td>\n",
        "      <td>man</td>\n",
        "      <td>True</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>890</td>\n",
        "      <td>0</td>\n",
        "      <td>3</td>\n",
        "      <td>32.0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>7.7500</td>\n",
        "      <td>Q</td>\n",
        "      <td>man</td>\n",
        "      <td>True</td>\n",
        "    </tr>\n",
        "  </tbody>\n",
        "</table>\n",
        "<p>712 rows × 9 columns</p>\n",
        "</div>"
       ],
       "text/plain": [
        "     survived  pclass   age  sibsp  parch     fare embarked    who  alone\n",
        "0           0       3  22.0      1      0   7.2500        S    man  False\n",
        "1           1       1  38.0      1      0  71.2833        C  woman  False\n",
        "2           1       3  26.0      0      0   7.9250        S  woman   True\n",
        "3           1       1  35.0      1      0  53.1000        S  woman  False\n",
        "4           0       3  35.0      0      0   8.0500        S    man   True\n",
        "..        ...     ...   ...    ...    ...      ...      ...    ...    ...\n",
        "885         0       3  39.0      0      5  29.1250        Q  woman  False\n",
        "886         0       2  27.0      0      0  13.0000        S    man   True\n",
        "887         1       1  19.0      0      0  30.0000        S  woman   True\n",
        "889         1       1  26.0      0      0  30.0000        C    man   True\n",
        "890         0       3  32.0      0      0   7.7500        Q    man   True\n",
        "\n",
        "[712 rows x 9 columns]"
       ]
      },
      "execution_count": 7,
      "metadata": {},
      "output_type": "execute_result"
     }
    ],
    "source": [
     "titanic"
    ]
   },
   {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
     "## 逻辑回归"
    ]
   },
   {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
     "### 导入包"
    ]
   },
   {
    "cell_type": "code",
    "execution_count": 8,
    "metadata": {},
    "outputs": [],
    "source": [
     "from sklearn.linear_model import LogisticRegression\n",
     "import numpy as np\n",
     "import matplotlib.pyplot as plt\n",
     "import pandas as pd\n",
     "from sklearn import model_selection#拆分训练集和测试集\n",
     "from sklearn.metrics import confusion_matrix#输出混淆矩阵"
    ]
   },
   {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
     "### 数值化处理"
    ]
   },
   {
    "cell_type": "code",
    "execution_count": 9,
    "metadata": {},
    "outputs": [],
    "source": [
     "titanic_dummy = pd.get_dummies(titanic[['who', 'embarked','alone']])"
    ]
   },
   {
    "cell_type": "code",
    "execution_count": 10,
    "metadata": {},
    "outputs": [],
    "source": [
     "titanic_conti = pd.DataFrame(titanic, columns=['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare'], index=titanic.index)\n",
     "titanic = titanic_conti.join(titanic_dummy)"
    ]
   },
   {
    "cell_type": "code",
    "execution_count": 11,
    "metadata": {},
    "outputs": [
     {
      "data": {
       "text/html": [
        "<div>\n",
        "<style scoped>\n",
        "    .dataframe tbody tr th:only-of-type {\n",
        "        vertical-align: middle;\n",
        "    }\n",
        "\n",
        "    .dataframe tbody tr th {\n",
        "        vertical-align: top;\n",
        "    }\n",
        "\n",
        "    .dataframe thead th {\n",
        "        text-align: right;\n",
        "    }\n",
        "</style>\n",
        "<table border=\"1\" class=\"dataframe\">\n",
        "  <thead>\n",
        "    <tr style=\"text-align: right;\">\n",
        "      <th></th>\n",
        "      <th>survived</th>\n",
        "      <th>pclass</th>\n",
        "      <th>age</th>\n",
        "      <th>sibsp</th>\n",
        "      <th>parch</th>\n",
        "      <th>fare</th>\n",
        "      <th>alone</th>\n",
        "      <th>who_child</th>\n",
        "      <th>who_man</th>\n",
        "      <th>who_woman</th>\n",
        "      <th>embarked_C</th>\n",
        "      <th>embarked_Q</th>\n",
        "      <th>embarked_S</th>\n",
        "    </tr>\n",
        "  </thead>\n",
        "  <tbody>\n",
        "    <tr>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>3</td>\n",
        "      <td>22.0</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>7.2500</td>\n",
        "      <td>False</td>\n",
        "      <td>0</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>1</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>1</td>\n",
        "      <td>1</td>\n",
        "      <td>1</td>\n",
        "      <td>38.0</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>71.2833</td>\n",
        "      <td>False</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>1</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>2</td>\n",
        "      <td>1</td>\n",
        "      <td>3</td>\n",
        "      <td>26.0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>7.9250</td>\n",
        "      <td>True</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>1</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>3</td>\n",
        "      <td>1</td>\n",
        "      <td>1</td>\n",
        "      <td>35.0</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>53.1000</td>\n",
        "      <td>False</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>1</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>4</td>\n",
        "      <td>0</td>\n",
        "      <td>3</td>\n",
        "      <td>35.0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>8.0500</td>\n",
        "      <td>True</td>\n",
        "      <td>0</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>1</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "      <td>...</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>885</td>\n",
        "      <td>0</td>\n",
        "      <td>3</td>\n",
        "      <td>39.0</td>\n",
        "      <td>0</td>\n",
        "      <td>5</td>\n",
        "      <td>29.1250</td>\n",
        "      <td>False</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>886</td>\n",
        "      <td>0</td>\n",
        "      <td>2</td>\n",
        "      <td>27.0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>13.0000</td>\n",
        "      <td>True</td>\n",
        "      <td>0</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>1</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>887</td>\n",
        "      <td>1</td>\n",
        "      <td>1</td>\n",
        "      <td>19.0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>30.0000</td>\n",
        "      <td>True</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>1</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>889</td>\n",
        "      <td>1</td>\n",
        "      <td>1</td>\n",
        "      <td>26.0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>30.0000</td>\n",
        "      <td>True</td>\n",
        "      <td>0</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>890</td>\n",
        "      <td>0</td>\n",
        "      <td>3</td>\n",
        "      <td>32.0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>7.7500</td>\n",
        "      <td>True</td>\n",
        "      <td>0</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "    </tr>\n",
        "  </tbody>\n",
        "</table>\n",
        "<p>712 rows × 13 columns</p>\n",
        "</div>"
       ],
       "text/plain": [
        "     survived  pclass   age  sibsp  parch     fare  alone  who_child  who_man  \\\n",
        "0           0       3  22.0      1      0   7.2500  False          0        1   \n",
        "1           1       1  38.0      1      0  71.2833  False          0        0   \n",
        "2           1       3  26.0      0      0   7.9250   True          0        0   \n",
        "3           1       1  35.0      1      0  53.1000  False          0        0   \n",
        "4           0       3  35.0      0      0   8.0500   True          0        1   \n",
        "..        ...     ...   ...    ...    ...      ...    ...        ...      ...   \n",
        "885         0       3  39.0      0      5  29.1250  False          0        0   \n",
        "886         0       2  27.0      0      0  13.0000   True          0        1   \n",
        "887         1       1  19.0      0      0  30.0000   True          0        0   \n",
        "889         1       1  26.0      0      0  30.0000   True          0        1   \n",
        "890         0       3  32.0      0      0   7.7500   True          0        1   \n",
        "\n",
        "     who_woman  embarked_C  embarked_Q  embarked_S  \n",
        "0            0           0           0           1  \n",
        "1            1           1           0           0  \n",
        "2            1           0           0           1  \n",
        "3            1           0           0           1  \n",
        "4            0           0           0           1  \n",
        "..         ...         ...         ...         ...  \n",
        "885          1           0           1           0  \n",
        "886          0           0           0           1  \n",
        "887          1           0           0           1  \n",
        "889          0           1           0           0  \n",
        "890          0           0           1           0  \n",
        "\n",
        "[712 rows x 13 columns]"
       ]
      },
      "execution_count": 11,
      "metadata": {},
      "output_type": "execute_result"
     }
    ],
    "source": [
     "titanic"
    ]
   },
   {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
     "### 逻辑回归"
    ]
   },
   {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
     "#### 划分训练集和测试集"
    ]
   },
   {
    "cell_type": "code",
    "execution_count": 12,
    "metadata": {},
    "outputs": [],
    "source": [
     "X = titanic.iloc[:, 1:]\n",
     "y = titanic.iloc[:, 0]\n",
     "X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.3, random_state=0)"
    ]
   },
   {
    "cell_type": "code",
    "execution_count": 13,
    "metadata": {},
    "outputs": [],
    "source": [
     "# 基于训练集使用逻辑回归建模\n",
     "classifier = LogisticRegression(random_state=0,solver='liblinear')\n",
     "classifier.fit(X_train, y_train)\n",
     " \n",
     "# 将模型应用于测试集并查看混淆矩阵\n",
     "y_pred = classifier.predict(X_test)"
    ]
   },
   {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
     "#### 混淆矩阵分析"
    ]
   },
   {
    "cell_type": "code",
    "execution_count": 14,
    "metadata": {},
    "outputs": [
     {
      "name": "stdout",
      "output_type": "stream",
      "text": [
       "[[105  20]\n",
       " [ 27  62]]\n"
      ]
     }
    ],
    "source": [
     "confusion_matrix = confusion_matrix(y_test, y_pred)\n",
     "print(confusion_matrix)  "
    ]
   },
   {
    "cell_type": "code",
    "execution_count": 15,
    "metadata": {},
    "outputs": [
     {
      "data": {
       "text/plain": [
        "0.780373831775701"
       ]
      },
      "execution_count": 15,
      "metadata": {},
      "output_type": "execute_result"
     }
    ],
    "source": [
     "classifier.score(X_test, y_test)#正确率"
    ]
   },
   {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
     "## 例二：面膜数据可视化"
    ]
   },
   {
    "cell_type": "code",
    "execution_count": 16,
    "metadata": {},
    "outputs": [],
    "source": [
     "import pandas as pd\n",
     "import matplotlib.pyplot as plt\n",
     "import seaborn as sns\n",
     "import numpy as np\n",
     "\n",
     "#解决中文显示问题\n",
     "from pylab import *  \n",
     "mpl.rcParams['font.sans-serif'] = ['SimHei'] #用来正常显示中文标签\n",
     "plt.rcParams['axes.unicode_minus'] = False  #用来正常显示负号"
    ]
   },
   {
    "cell_type": "code",
    "execution_count": 17,
    "metadata": {},
    "outputs": [
     {
      "data": {
       "text/html": [
        "<div>\n",
        "<style scoped>\n",
        "    .dataframe tbody tr th:only-of-type {\n",
        "        vertical-align: middle;\n",
        "    }\n",
        "\n",
        "    .dataframe tbody tr th {\n",
        "        vertical-align: top;\n",
        "    }\n",
        "\n",
        "    .dataframe thead th {\n",
        "        text-align: right;\n",
        "    }\n",
        "</style>\n",
        "<table border=\"1\" class=\"dataframe\">\n",
        "  <thead>\n",
        "    <tr style=\"text-align: right;\">\n",
        "      <th></th>\n",
        "      <th>名称</th>\n",
        "      <th>价格</th>\n",
        "      <th>月销量</th>\n",
        "      <th>评价数</th>\n",
        "      <th>店铺所在地</th>\n",
        "      <th>适合肤质</th>\n",
        "      <th>产地</th>\n",
        "      <th>补水保湿</th>\n",
        "      <th>美白提亮</th>\n",
        "      <th>控油祛痘</th>\n",
        "      <th>清洁毛孔</th>\n",
        "      <th>提拉紧致</th>\n",
        "    </tr>\n",
        "  </thead>\n",
        "  <tbody>\n",
        "    <tr>\n",
        "      <td>0</td>\n",
        "      <td>ANGLEE</td>\n",
        "      <td>254.0</td>\n",
        "      <td>40</td>\n",
        "      <td>3133</td>\n",
        "      <td>湖南</td>\n",
        "      <td>任何肤质</td>\n",
        "      <td>中国</td>\n",
        "      <td>1</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>1</td>\n",
        "      <td>ANGLEE</td>\n",
        "      <td>350.0</td>\n",
        "      <td>62</td>\n",
        "      <td>876</td>\n",
        "      <td>浙江</td>\n",
        "      <td>任何肤质</td>\n",
        "      <td>中国</td>\n",
        "      <td>1</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>2</td>\n",
        "      <td>ANGLEE</td>\n",
        "      <td>284.9</td>\n",
        "      <td>12</td>\n",
        "      <td>16</td>\n",
        "      <td>浙江</td>\n",
        "      <td>任何肤质</td>\n",
        "      <td>中国</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>1</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>3</td>\n",
        "      <td>BF</td>\n",
        "      <td>289.0</td>\n",
        "      <td>32</td>\n",
        "      <td>175</td>\n",
        "      <td>英国</td>\n",
        "      <td>任何肤质</td>\n",
        "      <td>中国</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "    </tr>\n",
        "    <tr>\n",
        "      <td>4</td>\n",
        "      <td>BSR</td>\n",
        "      <td>379.9</td>\n",
        "      <td>1407</td>\n",
        "      <td>13870</td>\n",
        "      <td>安徽</td>\n",
        "      <td>任何肤质</td>\n",
        "      <td>中国</td>\n",
        "      <td>1</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "      <td>0</td>\n",
        "    </tr>\n",
        "  </tbody>\n",
        "</table>\n",
        "</div>"
       ],
       "text/plain": [
        "       名称     价格   月销量    评价数 店铺所在地  适合肤质  产地  补水保湿  美白提亮  控油祛痘  清洁毛孔  提拉紧致\n",
        "0  ANGLEE  254.0    40   3133    湖南  任何肤质  中国     1     1     0     0     0\n",
        "1  ANGLEE  350.0    62    876    浙江  任何肤质  中国     1     1     0     0     0\n",
        "2  ANGLEE  284.9    12     16    浙江  任何肤质  中国     1     0     1     1     0\n",
        "3      BF  289.0    32    175    英国  任何肤质  中国     1     0     0     0     0\n",
        "4     BSR  379.9  1407  13870    安徽  任何肤质  中国     1     0     0     0     0"
       ]
      },
      "execution_count": 17,
      "metadata": {},
      "output_type": "execute_result"
     }
    ],
    "source": [
     "mask = pd.read_csv('mask.csv',encoding=\"gbk\")   #数据来源狗熊会\n",
     "mask.head()"
    ]
   },
   {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
     "### 数据清洗"
    ]
   },
   {
    "cell_type": "code",
    "execution_count": 18,
    "metadata": {},
    "outputs": [
     {
      "name": "stdout",
      "output_type": "stream",
      "text": [
       "['中国' '日本' '韩国' '美国' '英国' '其他/other']\n",
       "['湖南' '浙江' '英国' '安徽' '广东' '湖北' '江苏' '上海' '江西' '北京' '海外' '天津' '山东' '河南'\n",
       " '新加坡' '河北' '辽宁' '四川' '重庆' '福建' '内蒙古' '海南' '云南' '广西' '陕西' '黑龙江']\n",
       "['任何肤质' '干性肤质' '油性及混合性肤质' '中性及干性肤质' '混合型肤质' '敏感性肤质' '中性肤质' '油性肤质']\n"
      ]
     }
    ],
    "source": [
     "print(mask['产地'].unique())\n",
     "print(mask['店铺所在地'].unique())\n",
     "print(mask['适合肤质'].unique())"
    ]
   },
   {
    "cell_type": "code",
    "execution_count": 19,
    "metadata": {},
    "outputs": [],
    "source": [
     "mask.loc[mask.店铺所在地 == '英国','店铺所在地']= '海外'\n",
     "mask.loc[mask.店铺所在地 == '新加坡','店铺所在地'] = '海外'\n",
     "mask.loc[mask.产地 == '其他/other','产地'] = '其他'\n",
     "mask.loc[mask.适合肤质 != '任何肤质','适合肤质'] = '其他'"
    ]
   },
   {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
     "### 数据可视化"
    ]
   },
   {
    "cell_type": "code",
    "execution_count": 20,
    "metadata": {},
    "outputs": [
     {
      "data": {
       "text/plain": [
        "<matplotlib.axes._subplots.AxesSubplot at 0x1a1e0b1450>"
       ]
      },
      "execution_count": 20,
      "metadata": {},
      "output_type": "execute_result"
     },
     {
      "data": {
       "image/png": "iVBORw0KGgoAAAANSUhEUgAAAtMAAAE9CAYAAADJUu5eAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjEsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy8QZhcZAAAUqklEQVR4nO3df4xlZ3kf8O9jbyCB1rJhx2C8dtdQQ2MiENZguSRUFAqYlGALQWQKZAVGm7YugSZRMOUPO6oskTYpAUpRt2CwK2LXcgh2I0pwXQhBqYG1wy/boWxMai827BB+RaQyXXj6x1wn02XWnn13ztyZ3c9HWs09zzn3fZ6r/eero/eeW90dAADgyJ0w7wEAAGCrEqYBAGCQMA0AAIOEaQAAGCRMAwDAIGEaAAAGbZv3AEdj+/btvXPnznmPAQDAMe622277RncvHFrf0mF6586d2bt377zHAADgGFdV/3u1um0eAAAwSJgGAIBBwjQAAAwSpgEAYJAwDQAAg4RpAAAYJEwDAMAgYRoAAAYJ0wAAMEiYBgCAQZOF6aq6qqoOVNUXD6m/vqq+VFV3VNW/WVF/c1Xtm5174VRzAQDAetk24drvT/Lvk1zzYKGq/mGSC5M8rbsfqKpTZ/Vzklyc5KlJnpDkv1fVk7v7B2tt9rhnv34dR/8bX/+jd06yLgAAW99kd6a7+xNJvnlI+Z8leWt3PzC75sCsfmGS67r7ge7+SpJ9Sc6bajYAAFgPG71n+slJnl1Vn6qqP6yqZ87qpye5d8V1+2c1AADYtKbc5nG4fqckOT/JM5NcX1VPTFKrXNurLVBVu5PsTpIzzzxzojEBAODhbfSd6f1JPtjLPp3kh0m2z+pnrLhuR5L7Vlugu/d092J3Ly4sLEw+MAAAHM5Gh+kPJXluklTVk5M8Isk3ktyU5OKqemRVnZXk7CSf3uDZAADgiEy2zaOqrk3ynCTbq2p/ksuTXJXkqtnj8r6fZFd3d5I7qur6JHcmOZjk0iN5kgcAAMzDZGG6u19xmFOvOsz1Vya5cqp5AABgvfkFRAAAGCRMAwDAIGEaAAAGCdMAADBImAYAgEHCNAAADBKmAQBgkDANAACDhGkAABgkTAMAwCBhGgAABm2b9wBb1WkvfMsk697/B1dOsi4AAOvPnWkAABgkTAMAwCBhGgAABgnTAAAwSJgGAIBBwjQAAAwSpgEAYJAwDQAAg4RpAAAYJEwDAMAgYRoAAAZNFqar6qqqOlBVX1zl3K9WVVfV9tlxVdU7qmpfVX2+qs6dai4AAFgvU96Zfn+SCw4tVtUZSZ6f5J4V5RclOXv2b3eSd084FwAArIvJwnR3fyLJN1c59bYkv5akV9QuTHJNL7s1yclVddpUswEAwHrY0D3TVfWSJF/t7s8dcur0JPeuON4/qwEAwKa1baMaVdWjkrwlyQtWO71KrVeppap2Z3krSM4888x1mw8AAI7URt6ZflKSs5J8rqr+PMmOJLdX1eOzfCf6jBXX7khy32qLdPee7l7s7sWFhYWJRwYAgMPbsDDd3V/o7lO7e2d378xygD63u7+W5KYkvzB7qsf5Sb7T3fdv1GwAADBiykfjXZvkfyZ5SlXtr6pLHuLyDye5O8m+JP8pyT+fai4AAFgvk+2Z7u5XPMz5nSted5JLp5oFAACm4BcQAQBgkDANAACDhGkAABgkTAMAwCBhGgAABgnTAAAwaMN+Tpyjc/pFb51k3a9+6LJJ1gUAOB64Mw0AAIOEaQAAGCRMAwDAIGEaAAAGCdMAADBImAYAgEHCNAAADBKmAQBgkDANAACDhGkAABgkTAMAwCBhGgAABgnTAAAwSJgGAIBBwjQAAAwSpgEAYNBkYbqqrqqqA1X1xRW1f1tVf1pVn6+q36uqk1ece3NV7auqL1XVC6eaCwAA1suUd6bfn+SCQ2o3J/mp7n5akv+V5M1JUlXnJLk4yVNn7/kPVXXihLMBAMBRmyxMd/cnknzzkNpHu/vg7PDWJDtmry9Mcl13P9DdX0myL8l5U80GAADrYZ57pl+b5L/NXp+e5N4V5/bPagAAsGnNJUxX1VuSHEzygQdLq1zWh3nv7qraW1V7l5aWphoRAAAe1oaH6araleTFSV7Z3Q8G5v1Jzlhx2Y4k9632/u7e092L3b24sLAw7bAAAPAQNjRMV9UFSd6U5CXd/VcrTt2U5OKqemRVnZXk7CSf3sjZAADgSG2bauGqujbJc5Jsr6r9SS7P8tM7Hpnk5qpKklu7+5929x1VdX2SO7O8/ePS7v7BVLMBAMB6mCxMd/crVim/9yGuvzLJlVPNAwAA680vIAIAwCBhGgAABgnTAAAwSJgGAIBBwjQAAAwSpgEAYJAwDQAAg4RpAAAYJEwDAMAgYRoAAAYJ0wAAMEiYBgCAQcI0AAAMEqYBAGCQMA0AAIOEaQAAGCRMAwDAIGEaAAAGCdMAADBImAYAgEHCNAAADBKmAQBgkDANAACDJgvTVXVVVR2oqi+uqD2mqm6uqi/P/p4yq1dVvaOq9lXV56vq3KnmAgCA9TLlnen3J7ngkNplSW7p7rOT3DI7TpIXJTl79m93kndPOBcAAKyLycJ0d38iyTcPKV+Y5OrZ66uTXLSifk0vuzXJyVV12lSzAQDAetjoPdOP6+77k2T299RZ/fQk9664bv+sBgAAm9Zm+QJirVLrVS+s2l1Ve6tq79LS0sRjAQDA4W10mP76g9s3Zn8PzOr7k5yx4rodSe5bbYHu3tPdi929uLCwMOmwAADwUDY6TN+UZNfs9a4kN66o/8LsqR7nJ/nOg9tBAABgs9o21cJVdW2S5yTZXlX7k1ye5K1Jrq+qS5Lck+Tls8s/nORnk+xL8ldJXjPVXAAAsF4mC9Pd/YrDnHreKtd2kkunmgUAAKawWb6ACAAAW44wDQAAg4RpAAAYJEwDAMAgYRoAAAYJ0wAAMEiYBgCAQWsK01V1y1pqAABwPHnIH22pqh9P8qgs/4rhKUlqduqkJE+YeDYAANjUHu4XEH8xyRuzHJxvy9+E6e8medeEcwEAwKb3kGG6u9+e5O1V9frufucGzQQAAFvCw92ZTpJ09zur6llJdq58T3dfM9FcAACw6a0pTFfVf07ypCSfTfKDWbmTCNMAABy31hSmkywmOae7e8phAABgK1lrmP5ikscnuX/CWdhEnvhP3j7Junf/zhsmWRcAYB7WGqa3J7mzqj6d5IEHi939kkmmAgCALWCtYfqKKYcAAICtaK1P8/jDqQcBAICtZq1P8/jLLD+9I0kekeTHknyvu0+aajAAANjs1npn+m+vPK6qi5KcN8lEAACwRZww8qbu/lCS567zLAAAsKWsdZvHS1ccnpDl50575jQAAMe1tT7N4+dWvD6Y5M+TXLju0wAAwBay1j3Tr1nPplX1L5O8Lst3t7+Q5DVJTktyXZLHJLk9yau7+/vr2RcAANbTmvZMV9WOqvq9qjpQVV+vqt+tqh0jDavq9CS/lGSxu38qyYlJLk7yG0ne1t1nJ/lWkktG1gcAgI2y1i8gvi/JTUmekOT0JP91Vhu1LclPVNW2JI/K8s+UPzfJDbPzVye56CjWBwCAya01TC909/u6++Ds3/uTLIw07O6vJvnNJPdkOUR/J8ltSb7d3Qdnl+3PcmgHAIBNa61h+htV9aqqOnH271VJ/mKkYVWdkuUvL56V5Tvdj07yolUuXfVpIVW1u6r2VtXepaWlkREAAGBdrDVMvzbJzyf5WpbvJr8sy18aHPGPknylu5e6+/8m+WCSZyU5ebbtI0l2JLlvtTd3957uXuzuxYWFoZvjAACwLtYapv91kl3dvdDdp2Y5XF8x2POeJOdX1aOqqpI8L8mdST6W5ZCeJLuS3Di4PgAAbIi1humndfe3Hjzo7m8mecZIw+7+VJa/aHh7lh+Ld0KSPUnelOSXq2pfkscmee/I+gAAsFHW+qMtJ1TVKQ8G6qp6zBG890d09+VJLj+kfHeS80bXBACAjbbWQPxbSf64qm7I8hcDfz7JlZNNBQAAW8BafwHxmqram+VnQVeSl3b3nZNOBgAAm9yat2rMwrMADQAAM2v9AiIAAHAIYRoAAAYJ0wAAMEiYBgCAQcI0AAAMEqYBAGCQMA0AAIOEaQAAGCRMAwDAIGEaAAAGCdMAADBImAYAgEHCNAAADBKmAQBgkDANAACDhGkAABgkTAMAwCBhGgAABgnTAAAwSJgGAIBBcwnTVXVyVd1QVX9aVXdV1d+vqsdU1c1V9eXZ31PmMRsAAKzVvO5Mvz3JR7r77yV5epK7klyW5JbuPjvJLbNjAADYtDY8TFfVSUn+QZL3Jkl3f7+7v53kwiRXzy67OslFGz0bAAAciXncmX5ikqUk76uqP6mq91TVo5M8rrvvT5LZ31PnMBsAAKzZPML0tiTnJnl3dz8jyfdyBFs6qmp3Ve2tqr1LS0tTzQgAAA9rHmF6f5L93f2p2fENWQ7XX6+q05Jk9vfAam/u7j3dvdjdiwsLCxsyMAAArGbDw3R3fy3JvVX1lFnpeUnuTHJTkl2z2q4kN270bAAAcCS2zanv65N8oKoekeTuJK/JcrC/vqouSXJPkpfPaTbm4JzX7Zlk3Tvfs3uSdQEAkjmF6e7+bJLFVU49b6NnAQCAUX4BEQAABgnTAAAwSJgGAIBBwjQAAAwSpgEAYJAwDQAAg4RpAAAYJEwDAMAgYRoAAAYJ0wAAMEiYBgCAQcI0AAAMEqYBAGCQMA0AAIOEaQAAGCRMAwDAIGEaAAAGCdMAADBImAYAgEHCNAAADBKmAQBgkDANAACDhGkAABg0tzBdVSdW1Z9U1e/Pjs+qqk9V1Zer6r9U1SPmNRsAAKzFPO9MvyHJXSuOfyPJ27r77CTfSnLJXKYCAIA1mkuYrqodSf5xkvfMjivJc5PcMLvk6iQXzWM2AABYq3ndmf7tJL+W5Iez48cm+XZ3H5wd709y+jwGAwCAtdrwMF1VL05yoLtvW1le5dI+zPt3V9Xeqtq7tLQ0yYwAALAW2+bQ86eTvKSqfjbJjyc5Kct3qk+uqm2zu9M7kty32pu7e0+SPUmyuLi4auCGh3LuL1092dq3v2PXZGsDAJvPht+Z7u43d/eO7t6Z5OIk/6O7X5nkY0leNrtsV5IbN3o2AAA4EpvpOdNvSvLLVbUvy3uo3zvneQAA4CHNY5vHX+vujyf5+Oz13UnOm+c8AABwJDbTnWkAANhShGkAABgkTAMAwCBhGgAABgnTAAAwSJgGAIBBc300HhwPfuay6yZb+5NvvfhHas//9Q9O1u/my1862doAsBW5Mw0AAIOEaQAAGCRMAwDAIGEaAAAGCdMAADBImAYAgEHCNAAADBKmAQBgkDANAACDhGkAABgkTAMAwCBhGgAABm2b9wDA1nbRb/7+ZGt/6FdfPNnaALAe3JkGAIBBwjQAAAwSpgEAYNCGh+mqOqOqPlZVd1XVHVX1hln9MVV1c1V9efb3lI2eDQAAjsQ87kwfTPIr3f2TSc5PcmlVnZPksiS3dPfZSW6ZHQMAwKa14WG6u+/v7ttnr/8yyV1JTk9yYZKrZ5ddneSijZ4NAACOxFz3TFfVziTPSPKpJI/r7vuT5cCd5NT5TQYAAA9vbmG6qv5Wkt9N8sbu/u4RvG93Ve2tqr1LS0vTDQgAAA9jLmG6qn4sy0H6A939wVn561V12uz8aUkOrPbe7t7T3YvdvbiwsLAxAwMAwCrm8TSPSvLeJHd1979bceqmJLtmr3cluXGjZwMAgCMxj58T/+kkr07yhar67Kz2r5K8Ncn1VXVJknuSvHwOswGb3Cvf9dFJ1v3ApS+YZF0Ajm0bHqa7+5NJ6jCnn7eRswAAwNHwC4gAADBImAYAgEHCNAAADBKmAQBgkDANAACDhGkAABgkTAMAwCBhGgAABgnTAAAwSJgGAIBBwjQAAAwSpgEAYNC2eQ8AsJn94lUfn2Td//ja56xa/5Vr/3iSfr/1imdNsi7A8c6daQAAGCRMAwDAIGEaAAAG2TMNcBz79Rv3TrLu5RcuTrIuwGbjzjQAAAwSpgEAYJBtHgBsmN/+6OcmWfeNL3j6qvWr/ujOSfq99tnnTLIusPUI0wCwDm74zL7J1n7ZM//uZGsDR8c2DwAAGOTONABsQR/53D2TrX3B08/8kdon77p/sn4/85On/Ujt9j/7xmT9zn3S9snW5viz6e5MV9UFVfWlqtpXVZfNex4AADicTXVnuqpOTPKuJM9Psj/JZ6rqpu6e5hskAABJ7rjnW5Os+9QzT1m1/mdf++4k/Z70+JMmWZfD21RhOsl5SfZ1991JUlXXJbkwiTANADDo3r/43iTrnvHYR69aX/ruA5P0WzjpkavWv/t/Dk7S76SfePiovNm2eZye5N4Vx/tnNQAA2HSqu+c9w1+rqpcneWF3v252/Ook53X361dcszvJ7tnhU5J8aaDV9iTTfbNBP/22Tr9j+bPpp59+8+t3LH82/Y7ffn+nuxcOLW62bR77k5yx4nhHkvtWXtDde5LsOZomVbW3uxePZg399DsW+h3Ln00//fSbX79j+bPpp9+hNts2j88kObuqzqqqRyS5OMlNc54JAABWtanuTHf3war6F0n+IMmJSa7q7jvmPBYAAKxqU4XpJOnuDyf58MRtjmqbiH76HUP9juXPpp9++s2v37H82fTT7/+zqb6ACAAAW8lm2zMNAABbhjANAACDhGkAABi06b6AuN6q6ook5yd58HcmtyW5dbVad1+xlfody59NP/30m1+/Y/mz6aeffkfWY/Z6uPdG9jqa3kfzf3fMh+mZi7v720lSVScneeNhalux37H82fTTT7/59TuWP5t++ul3ZD2OtvdG9jqa3kNs8wAAgEHCNAAADBKmAQBgkDANAACDhGkAABgkTAMAwKDj4dF4B5JcU1U/nB2fkOQjh6lttX7H8mfTTz/95tfvWP5s+umn35H3OJreG9nraHsPqe4+mvcDAMBxyzYPAAAYJEwDAMAgYRoAAAYJ0wAAMOh4eJoHwDGpqq5Icn6Sg7PStiS3HqaW9ah39xXr+RkAtjphGmBru7i7v50kVXVykjcepna4a0fqAMzY5gEAAIOEaQAAGCRMAwDAIGEaAAAGCdMAADBImAYAgEEejQewdR1Ick1V/XB2fEKSjxymlnWsAzBT3T3vGQAAYEuyzQMAAAYJ0wAAMEiYBgCAQcI0AAAMEqYBAGDQ/wPoMtMH3HDbewAAAABJRU5ErkJggg==\n",
       "text/plain": [
        "<Figure size 864x360 with 1 Axes>"
       ]
      },
      "metadata": {
       "needs_background": "light"
      },
      "output_type": "display_data"
     }
    ],
    "source": [
     "plt.figure(figsize=(12,5))\n",
     "sns.countplot('店铺所在地',data=mask,order = mask['店铺所在地'].value_counts().index,palette='Blues_r')"
    ]
   },
   {
    "cell_type": "code",
    "execution_count": null,
    "metadata": {},
    "outputs": [],
    "source": []
   },